# spring boot 项目的基础配置
spring:
  application:
    name: 01.Spring-Boot-Servlet-Component
# 应用的端口相关设置（如果是部署到tomcat中，此处端口不需要配置开发与生产）
server:
  port: 8080  # 默认也是8080
  servlet:
    # 项目contextPath
    context-path: /
    tomcat:
      # tomcat的URI编码
      uri-encoding: UTF-8
      # tomcat最大线程数，默认为200
      max-threads: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare-threads: 30